#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "CNAME", "LICENSE", "README.md", "AUTHORING.md"]

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "https://longtoothgamer.com"

include: ['_pages']

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

#######################################################
#######################################################
###############   HEADER INFORMATION   ###############
#######################################################
#######################################################

# This is your site title
title: Long Tooth Gamer

# Website language
lang: en-US

# Site Tagline
tagline: Technology and Gaming Info for Sensible Adults

# Header Title
header-title: Long Tooth Gamer

# Main contact email address
email: hello@longtoothgamer.com

####################################
######  Global Social Links   ######
####################################
youtube: "https://www.youtube.com/channel/UC8nJI40ZJ2C682oAsB16gCA"
facebook: "https://www.facebook.com/LongToothGamer/"
instagram: "https://www.instagram.com/longtoothgamer/"
twitter: "https://twitter.com/longtoothgamer"
tiktok: "https://www.tiktok.com/@longtoothgamer"
pinterest: "https://www.pinterest.com/LongToothGamer"

#########################
######   Widgets   ######
#########################

#
# About Vlog Author Widget
#
about-widget:
  author-avatar: Ray-Headshot-Simple.jpg
  author-name: Ray Cardillo
  author-tagline: Long Tooth Gamer
  author-info: >
    A professional Software Engineer and lifelong gamer who enjoys helping
    others embrace technology and gaming for good.
  author-social-links:
    youtube: "https://www.youtube.com/channel/UC8nJI40ZJ2C682oAsB16gCA"
    facebook: "https://www.facebook.com/LongToothGamer/"
    instagram: "https://www.instagram.com/longtoothgamer/"
    twitter: "https://twitter.com/longtoothgamer"

#####################################
#############   About   #############
#####################################
about-title: About Me
about-description-short: Long Tooth Gamer is produced by Ray Cardillo.
about-description-long: >
  I'm a content creator who enjoys helping older adults learn about computers,
  technology and gaming. I've been working with technology as long as I can
  remember and I have been a professional Software Engineer for over 30 years
  and counting. I particularly enjoy helping senior adults embrace technology.

#####################################
############# Vlog ##############
#####################################
vlog-title: My Vlog

#####################################
#############   Footer   ############
#####################################
footer-description: Find Long Tooth Gamer on all of your favorite sites.
footer-copyright-text: Cardillo's Creations, LLC
footer-copyright-link: https://cardilloscreations.com
footer-copyright-year: 2021
