#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md", "AUTHORING.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "https://longtoothgamer.com"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATION   ###############
#######################################################
#######################################################

# This is your site title
title: Long Tooth Gamer
# Website language
lang: en-US
# Header Title
header-title: Long Tooth Gamer
# Header Tagline
header-tagline: Gaming and Tech Tips for Sensible Adults

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hello@longtoothgamer.com

####################################
######  Global Social Links   ######
####################################
youtube: "https://www.youtube.com/channel/UC8nJI40ZJ2C682oAsB16gCA"
facebook: "https://www.facebook.com/LongToothGamer/"
instagram: "https://www.instagram.com/longtoothgamer/"
twitter: "https://twitter.com/longtoothgamer"
tiktok: "https://www.tiktok.com/@longtoothgamer"

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: Ray Cardillo
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: "#"
    facebook: "#"
    instagram: "#"
    twitter: "#"

#####################################
#############   About   #############
#####################################
about-title: About Me
about-description-short: Long Tooth Gamer is produced by Ray Cardillo.
about-description-long: >
  I'm a content creator who enjoys helping adults with gaming and technology.
  I've been working with computers as long as I can remember and have been a
  software engineer for over 30 years and counting. Aside from general advice,
  I particularly enjoy helping older adults embrace technology.

#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#####################################
#############   Footer   ############
#####################################
footer-description: Find Long Tooth Gamer on all of your favorite sites.
footer-copyright-text: Cardillo's Creations, LLC
footer-copyright-year: 2021
